module limits_declarations;

[[vk::constant_id(0)]]
public const uint32_t MAX_TASK_WORK_GROUP_COUNT_X = 4294967295;
[[vk::constant_id(1)]]
public const uint32_t MAX_TASK_WORK_GROUP_COUNT_Y = 65535;
[[vk::constant_id(2)]]
public const uint32_t MAX_TASK_WORK_GROUP_COUNT_Z = 65535;
[[vk::constant_id(3)]]
public const uint32_t MAX_MESH_WORK_GROUP_COUNT_X = 65535;
[[vk::constant_id(4)]]
public const uint32_t MAX_MESH_WORK_GROUP_COUNT_Y = 65535;
[[vk::constant_id(5)]]
public const uint32_t MAX_MESH_WORK_GROUP_COUNT_Z = 65535;