//
// Created by William on 2026-09-04.
//

#ifndef WILL_ENGINE_STRING_ID_TABLE_H
#define WILL_ENGINE_STRING_ID_TABLE_H

#include <cstddef>

#include "string_id.h"

namespace Core
{
struct StringLiteralEntry
{
    StringID id;
    const char* str;
};

/** Generated by scripts/gen_string_literals.py, sorted ascending by hash so it is binary-searchable as emitted. */
extern const StringLiteralEntry gSTRING_LITERALS[];
extern const size_t gSTRING_LITERAL_COUNT;

/**
 * Asserts the generated table is sorted by the engine's own hash and free of collisions.
 * Catches a drift between scripts/xxh3.py and the C++ XXH3, which would otherwise mis-sort the table.
 */
void VerifyStringLiteralTable();

/** @return the interned literal for `hash`, or nullptr if the table does not hold it. */
const char* FindStringLiteral(uint64_t hash);
}

#endif //WILL_ENGINE_STRING_ID_TABLE_H
