//
// Created by William on 2026-09-04.
//

#ifndef WILL_ENGINE_STRING_ID_TABLE_H
#define WILL_ENGINE_STRING_ID_TABLE_H

#include <cstddef>

#include "string_id.h"

namespace Core
{
struct StringLiteralEntry
{
    StringID id;
    const char* str;
};

/** Generated by scripts/gen_string_literals.py, sorted by literal text rather than by hash. */
extern const StringLiteralEntry gSTRING_LITERALS[];
extern const size_t gSTRING_LITERAL_COUNT;
}

#endif //WILL_ENGINE_STRING_ID_TABLE_H
