#!/usr/bin/env python3
"""
Extracts Sobol direction vectors from Joe & Kuo's direction numbers file and
outputs a Slang module with the constants and helper functions.

Usage:
    python extract_sobol.py <joe_kuo_file> [num_dimensions] > shaders/include/sobol_directions.slang

num_dimensions defaults to 4 (dims 0-3, sufficient for ReSTIR DI:
  dims 0,1 = light surface (uU, uV) per candidate
  dims 2,3 = BRDF importance sample (xi0, xi1))
"""

import sys


def compute_direction_vectors(s, a, m_values):
    V = [0] * 33  # 1-indexed
    for i in range(1, s + 1):
        V[i] = m_values[i - 1] << (32 - i)
    for i in range(s + 1, 33):
        V[i] = V[i - s] ^ (V[i - s] >> s)
        for k in range(1, s):
            if (a >> (s - 1 - k)) & 1:
                V[i] ^= V[i - k]
    return V[1:33]


def main():
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <joe_kuo_file> [num_dimensions]", file=sys.stderr)
        sys.exit(1)

    filename = sys.argv[1]
    num_dims = int(sys.argv[2]) if len(sys.argv) > 2 else 4

    all_dirs = []

    # Dimension 0: Van der Corput -- direction vectors are 1 << (31-i)
    all_dirs.append([1 << (31 - i) for i in range(32)])

    with open(filename) as f:
        next(f)  # skip header
        for line in f:
            if len(all_dirs) >= num_dims:
                break
            parts = line.split()
            if len(parts) < 4:
                continue
            s = int(parts[1])
            a = int(parts[2])
            m_values = [int(x) for x in parts[3:3 + s]]
            all_dirs.append(compute_direction_vectors(s, a, m_values))

    print("// AUTO-GENERATED by scripts/extract_sobol.py. Do not edit by hand.")
    print(f"// Source: Joe & Kuo direction numbers, {num_dims} dimensions.")
    print("// Dim 0 = Van der Corput. Dims 1+ from Joe-Kuo file.")
    print("module sobol_directions;")
    print()
    print(f"public static const uint SOBOL_DIRECTIONS[{num_dims}][32] =")
    print("{")
    for d, vecs in enumerate(all_dirs):
        label = "Van der Corput" if d == 0 else f"Joe-Kuo dim {d}"
        vals = ", ".join(f"0x{v:08x}u" for v in vecs)
        comma = "," if d < num_dims - 1 else ""
        print(f"    {{ {vals} }}{comma} // {label}")
    print("};")


main()
