#!/usr/bin/env python3
"""
Emits the compile-time StringID literal table, so ToString() can resolve a hash without
a runtime intern table.

    python scripts/gen_string_literals.py <output.cpp>
    python scripts/gen_string_literals.py --list        # print what would be collected

Collects two forms:
    "some literal"_sid
    static constexpr const char* COMPONENT_NAME = "SomeComponent";   (reaches StringID via TypeSID<T>)

Hashes are NOT computed here. The generated file emits Hash(lit, sizeof(lit) - 1) and lets the C++
constexpr evaluator do it, so this script cannot drift from the engine's XXH3 and needs no hash of
its own. It routes through Hash rather than the _sid literal because _sid is not constexpr under
WDEBUG (it interns), which would make the table dynamically initialised in exactly the builds that
need it. sizeof rather than a Python length so escaped literals stay correct.

xxh3.py IS used, but only to order the rows so the table ships binary-searchable. The engine asserts
that ordering at startup against its own hash, so a drift between the two implementations is caught
immediately rather than silently mis-sorting the table.

A literal this script fails to collect resolves to "unknown" at runtime. That is the same
degradation the old fixed-size intern buffer had on overflow, so missing one is not a crash.
"""
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import xxh3

SOURCE_ROOT = "src"
SOURCE_EXTS = (".cpp", ".h", ".hpp")

SID_LITERAL = re.compile(r'"((?:[^"\\]|\\.)*)"_sid')
COMPONENT_NAME = re.compile(r'COMPONENT_NAME\s*=\s*"((?:[^"\\]|\\.)*)"')


def _repo_root():
    return os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def strip_comments(text):
    out = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    return re.sub(r"//[^\n]*", "", out)


def collect(root=None):
    root = root or os.path.join(_repo_root(), SOURCE_ROOT)
    literals = set()
    for dirpath, _, filenames in os.walk(root):
        for filename in filenames:
            if not filename.endswith(SOURCE_EXTS):
                continue
            path = os.path.join(dirpath, filename)
            with open(path, "r", encoding="utf-8", errors="replace") as f:
                text = strip_comments(f.read())
            literals.update(SID_LITERAL.findall(text))
            literals.update(COMPONENT_NAME.findall(text))
    literals.discard("")
    # Sorted by hash so the table is binary-searchable as emitted. The C++ side asserts this
    # ordering at startup, so a drift between xxh3.py and the engine's XXH3 fails loudly.
    return sorted(literals, key=lambda s: (xxh3.string_id(s), s))


def emit(literals):
    lines = [
        "// Generated by scripts/gen_string_literals.py. Do not edit.",
        "",
        '#include "core/string_id_table.h"',
        "",
        "namespace Core",
        "{",
        "extern constinit const StringLiteralEntry gSTRING_LITERALS[] = {",
    ]
    for lit in literals:
        lines.append('    {{ StringID(Hash("{0}", sizeof("{0}") - 1)), "{0}" }},'.format(lit))
    lines.append("};")
    lines.append("")
    lines.append("extern const size_t gSTRING_LITERAL_COUNT = {};".format(len(literals)))
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main():
    args = sys.argv[1:]
    literals = collect()

    if not args or args[0] == "--list":
        for lit in literals:
            print(lit)
        print("--- {} unique literals".format(len(literals)), file=sys.stderr)
        return

    text = emit(literals)
    out_path = args[0]

    # Only rewrite when the content actually changes, so an unchanged run does not retrigger the build.
    if os.path.exists(out_path):
        with open(out_path, "r", encoding="utf-8") as f:
            if f.read() == text:
                return

    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(text)


if __name__ == "__main__":
    main()
