//
// Created by William on 2025-12-17.
//

#ifndef WILL_ENGINE_CONSTANTS_INTEROP_H
#define WILL_ENGINE_CONSTANTS_INTEROP_H

#ifdef __SLANG__
module constants_interop;
#define SHADER_PUBLIC public
#define SHADER_CONST const static
#else
#include <glm/glm.hpp>
#include <cstdint>

using uint = uint32_t;
using int32 = int32_t;
using uint32 = uint32_t;

using float2 = glm::vec2;
using float3 = glm::vec3;
using float4 = glm::vec4;

using int2 = glm::ivec2;
using int3 = glm::ivec3;
using int4 = glm::ivec4;

using uint2 = glm::uvec2;
using uint3 = glm::uvec3;
using uint4 = glm::uvec4;

using float2x2 = glm::mat2;
using float3x3 = glm::mat3;
using float4x4 = glm::mat4;

#define SHADER_PUBLIC
#define SHADER_CONST constexpr inline
#endif // __SLANG__

SHADER_PUBLIC SHADER_CONST uint32_t RDG_POINT_SAMPLER_INDEX = 0;
SHADER_PUBLIC SHADER_CONST uint32_t RDG_LINEAR_SAMPLER_INDEX = 1
;
SHADER_PUBLIC SHADER_CONST uint32_t RDG_LINEAR_DEPTH_SAMPLER_INDEX = 0;

SHADER_PUBLIC SHADER_CONST int32_t TASK_SHADER_DISPATCH_X = 64;
SHADER_PUBLIC SHADER_CONST int32_t MESH_SHADER_DISPATCH_X = 32;

SHADER_PUBLIC SHADER_CONST uint32_t MESHLET_MAX_VERTICES = 64;
SHADER_PUBLIC SHADER_CONST uint32_t MESHLET_MAX_TRIANGLES = 64;

SHADER_PUBLIC SHADER_CONST uint32_t INSTANCING_VISIBILITY_DISPATCH_X = 64;
SHADER_PUBLIC SHADER_CONST uint32_t INSTANCING_CONSTRUCTION_DISPATCH_X = 64;

SHADER_PUBLIC SHADER_CONST int32_t SHADOW_CASCADE_COUNT = 4;

SHADER_PUBLIC SHADER_CONST int32_t POST_PROCESS_LUMINANCE_DISPATCH_X = 16;
SHADER_PUBLIC SHADER_CONST int32_t POST_PROCESS_LUMINANCE_DISPATCH_Y = 16;
SHADER_PUBLIC SHADER_CONST int32_t POST_PROCESS_LUMINANCE_HISTOGRAM_SIZE = POST_PROCESS_LUMINANCE_DISPATCH_X * POST_PROCESS_LUMINANCE_DISPATCH_Y;

SHADER_PUBLIC SHADER_CONST int32_t POST_PROCESS_MOTION_BLUR_TILE_DISPATCH_X = 8;
SHADER_PUBLIC SHADER_CONST int32_t POST_PROCESS_MOTION_BLUR_TILE_DISPATCH_Y = 8;
SHADER_PUBLIC SHADER_CONST int32_t POST_PROCESS_MOTION_BLUR_TILE_SIZE = 20;
SHADER_PUBLIC SHADER_CONST int32_t POST_PROCESS_MOTION_BLUR_CONVOLUTION_DISPATCH_X = 8;
SHADER_PUBLIC SHADER_CONST int32_t POST_PROCESS_MOTION_BLUR_CONVOLUTION_DISPATCH_Y = 8;
SHADER_PUBLIC SHADER_CONST int32_t POST_PROCESS_MOTION_BLUR_SAMPLE_COUNT = 11;
SHADER_PUBLIC SHADER_CONST int32_t POST_PROCESS_MOTION_BLUR_DISPATCH_X = 16;
SHADER_PUBLIC SHADER_CONST int32_t POST_PROCESS_MOTION_BLUR_DISPATCH_Y = 16;

SHADER_PUBLIC SHADER_CONST int32_t POST_PROCESS_BLOOM_DISPATCH_X = 16;
SHADER_PUBLIC SHADER_CONST int32_t POST_PROCESS_BLOOM_DISPATCH_Y = 16;

SHADER_PUBLIC SHADER_CONST int32_t POST_PROCESS_VIGNETTE_ABERRATION_DISPATCH_X = 16;
SHADER_PUBLIC SHADER_CONST int32_t POST_PROCESS_VIGNETTE_ABERRATION_DISPATCH_Y = 16;

SHADER_PUBLIC SHADER_CONST int32_t POST_PROCESS_FILM_GRAIN_DISPATCH_X = 16;
SHADER_PUBLIC SHADER_CONST int32_t POST_PROCESS_FILM_GRAIN_DISPATCH_Y = 16;

SHADER_PUBLIC SHADER_CONST int32_t POST_PROCESS_SHARPENING_DISPATCH_X = 16;
SHADER_PUBLIC SHADER_CONST int32_t POST_PROCESS_SHARPENING_DISPATCH_Y = 16;

#endif //WILL_ENGINE_CONSTANTS_INTEROP_H